name: KatTomaszewski
favicon: null
layout_spectrum: 0.7521706100087613
typography_spectrum: 0.45961245335638523
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.6629886750597507
  lightness: 0.7457216437906027
  saturation: 0.5853467711713165
  rhythmicContrast: 0.1697282895911485
purpose: []
